### ISSUE TITLE
Proposal for optimization of menu

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/clearinghouse-ui#531]
**Menu**

It would be convenient if Menu will be organized in following order:

**Level 1:** 
•	Items Admin, Imports, **Project** (replacement for “Catalogue”; expandable) & **All Datasets** (replacement for “Datasets”, means, all datasets in the Clearinghouse. Children levels remain unchanged, only item “Sectors” should be excluded, because GSD sectors depend on parent Projects).
•	Would it be possible to use magnifier instead of gear icon for search?
•	Arrow down icon on the right – to expand menu for a next level
 
![image](https://user-images.githubusercontent.com/28574252/78188439-d7277f00-7435-11ea-9e6d-1332302ab666.png)
  
 
**Level 2** (the project selected, and Project items of 2nd level expanded)
•	Items **Project Details** (it includes all menu items related to the project, see Level 3), **Assemly** & **Source Datasets** (with option to search for GSD or go to full list of GSDs in the project).
•	If project selected, browser should remember this and open every session with the same project and expanded children, if they were expanded previously)

![image](https://user-images.githubusercontent.com/28574252/78188491-edcdd600-7435-11ea-8f36-263e80710acc.png)

  
**Level 3** (Project Details expanded)
•	Children in Project Details are the same, only Assembly item is moved to Level 2
•	If Project Details expanded for a third level, browser should remember this in next session

![image](https://user-images.githubusercontent.com/28574252/78188503-f7efd480-7435-11ea-9282-3034bb52661a.png)

 
**Level 3** (Source dataset selected, and Level 3 items expanded)
•	Short name and ID is shown
•	Children in Source: **Issues**, **Tasks**, **Workbench**, **Duplicates**, **Sectors**. We also need here items repeated from All Sources: **Metadata**, **Classification**, **References**, **Verbatim**, **Imports**.
•	If GSD selected, browser should remember this in next session
•	If Source expanded for a third level, browser should remember this in next session
•	Important: if user jump from Source to Assembly, expanded Level 3 children in Source (or in Project details), menu should stay expanded, and do not collapse

![image](https://user-images.githubusercontent.com/28574252/78188522-00e0a600-7436-11ea-8d36-e263e58a8d46.png)

**Comment by mdoering** [comment]
I like that @yroskov. May I ask why you want to elevate assembly out of all the other project menu items? A few further remarks:

I would just ask to keep "Datasets" instead of "All datasets".

Replacing "Source 1234" with "{Alias} {ID}" without the source prefix sounds great to me, just hope we can really limit all alias names to short strings. @thomasstjerne maybe the UI should simply cut longer ones off to avoid ugly line breaks

Please keep the sector menu item under the general dataset item. For dataset owners and the public it is important to know in which projects a dataset and what part of it is being used. It obviously needs to be slightly different from the project scoped one as we will have to show sectors from all projects, see https://github.com/CatalogueOfLife/clearinghouse-ui/issues/460#issuecomment-600727542. I would think it would be ideal to first have an overview of all projects that have at least one sector for the given dataset. And then one can drill into the sectors for a selected project. @thomasstjerne for this the backend should probably create a new more efficient API method, but thats simple. As a note that also all releases have their own sectors. So if there are 10 annual and 12 monthly CoL releases alone, all of them have their own sectors and it would be overwhelming to show them all here without a project scope.

**Comment by mdoering** [comment]
I find the "project details" submenu very irritating in practise. Why is assembly higher up in the menu structure and all the other parts hidden away? I would strongly suggest to rethink this arrangement.

**Comment by mdoering** [comment]
@thomasstjerne as we introduces 3d level menu items already I would suggest to also place the main Dataset menu under Datasets, so it sits below the search and recent items.

**Comment by yroskov** [comment]
@thomasstjerne Tests of Frontend version: a663ae3 April 8, 2020 4:27 AM at data.dev.catalogue.life.
**Useful feature** for my work: **all menus stay expanded, if I expanded them manually**. 
Present behavior: I selected ILDIS, made few manipulations there, then I need to check progress in Imports: expanded Imports, clucked on Running, and both Project and Source menus collapsed, to continue my work with ILDIS, I need to dig in menus again; even more irritating, I need to search for ILDIS again. If all menus stay expanded, as I left them, it will safe lot of editor's time.

**Comment by yroskov** [comment]
Project - SourceDataset [came to the page, waited for a full report on datasets]. How to navigate through a list of datasets quickly? - We need a search box on the left from IssueGroups items:

![image](https://user-images.githubusercontent.com/28574252/78832412-d13f1a00-79b0-11ea-8b8a-ad47152eb203.png)

**Comment by yroskov** [comment]
Comment to menu item **SelectSource**. In last two days of tests, I made numerous mistakes by clicking on SourceDatasets (woops! and now waiting for 15 sec) instead of clicking on SelectSource. How to improve interface to avoid common user's mistake? Replace item SelectSource with standard search icon to the right of SourceDatasets item.

Users will be more comfortable with a familiar search icon like this https://www.google.com/search?client=firefox-b-1-d&q=search+icon. 
![image](https://user-images.githubusercontent.com/28574252/78834312-05680a00-79b4-11ea-83d6-959096cbba4a.png)

(We would expect use of gear icon for settings).

**Comment by mdoering** [comment]
@thomasstjerne the public dataset should still have an Issues overview. We could restrict access  to editors for that dataset only, but it needs to be outside of a project, e.g. for data publishers to look at

**Comment by mdoering** [comment]
@thomasstjerne, @yroskov summary of remaining tasks AFAIK:

 - [ ] use search icon for SelectSource
 - [ ] keep all menus expanded, they only close manually
 - [ ] store last project in user settings and reload on login
 - [ ] move public Dataset under Datasets
 - [ ] add back Datasets.Dataset.Issues
 - [ ] Discuss "project details" on 3rd level vs Assembly on 2nd

**Comment by mdoering** [comment]
We seem to have lost the sectors menu item in both the project source dataset and public dataset menu:
https://data.catalogue.life/catalogue/3/dataset/1115/meta

**Comment by yroskov** [comment]
https://data.catalogue.life/catalogue/3/sector?limit=100&offset=0

**Comment by mdoering** [comment]
Ah yes, its only available for the project now. We need to add sth for the public datasets that is listing all projects the dataset contributes to.

**Comment by thomasstjerne** [comment]
It is still under public dataset view, just needs adjustment in first column to show project rather than source: https://data.catalogue.life/dataset/1115/sectors?limit=500&offset=0

**Comment by mdoering** [comment]
We still have not discussed:
> discuss project details on 3rd level vs Assembly on 2nd

Does it make much sense to hide the other project pages on the 3rd level ?

Also the project page is not done at all, but that is being discussed further already in #552 and #553

**Comment by yroskov** [comment]
**Assembly** on 2nd level makes my tasks much easier. There, I am identifying GSD sectors and assembling them in the Tree. This item is a medium between my actions inside GSD and inside project. Exactly, 2nd level in a menu.

**Comment by mdoering** [comment]
The menu can get very large now if a dataset is open under both a project and standalone. The redundancy of menu items also make things rather unintuitive. And the 3rd levels are quite deeply nested so you start losing context. I fear we jumped too quickly into implementing this proposal. 

Could we not have done sth simpler with just 2 levels? And trying not to mix the project view with the "global" datasets view in the same menu, but show just one of those views at a time? I would also find it better to show the project you are working in not in the menu but rather prominently in the header, e.g. next to the users login. So you would end up with 2 slightly different views and menus depending if you have selected a project or not. If a project is selected the UI URL would scope datasets under the project like /project/3/dataset/1234, without a project you get the /dataset/1234 URL.

Right now we have 4 main menu items. Admin and Imports could just be 2 top items (or maybe also sticky items at the bottom?). The 2 import items could easily be collapsed to just one page with a toggle button to switch between past and running imports.

Then we could raise all menu items from the project to one level higher so we only have 2 levels.
Similar with Datasets.

We could also try to collapse the datasets menu items to just one datasets item that shows the dataset search with a button to create new datasets. Even the recently visited datasets could be shown in the dataset search table by having another button next to the search to show the recent list instead of search results?

I stop here. Just ideas to simplify the menu, but I think we do need to revisit the menu structure and discuss this in one of our next calls extensively with demos.

**Comment by yroskov** [comment]
Markus, I have requested menu optimization because my job was completely blocked by previous implementations. I asked for changes, which I need to perform CoL assembly. I need menu for project in way as I described.

**Comment by mdoering** [comment]
Changing the menu did already cost a lot of time for @thomasstjerne, we should try to think about menu changes more coherently
