### ISSUE TITLE
Wrong dataset title

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/clearinghouse-ui#564]
When I paste this into a new Chrome browser window where I was logged in already in a different tab, I get the draft catalogue 3 as the selected project and its metadata displayed: https://data.dev.catalogue.life/dataset/31502/issues

When doing this in a new, incognito window its fine.

**Comment by mdoering** [comment]
it even doesnt change on forced reload:

<img width="1754" alt="Screenshot 2020-04-22 at 17 09 04" src="https://user-images.githubusercontent.com/327505/79999348-15a3dd00-84bc-11ea-99fe-1a1593c6ab91.png">

**Comment by thomasstjerne** [comment]
Not entirely sure, but could be due this: https://github.com/CatalogueOfLife/backend/issues/692

Because the new menu structure remembers your state you will end up in a stores state - which is immediately replaced when you paste paste in the link - however in this specific case, fetching dataset 31502 fails, and therefore you "stay" in the stored state.

**Comment by mdoering** [comment]
sounds reasonable. I'm not sure if CatalogueOfLife/backend#692 still is true though. In my case I think I pasted the URL to a private dataset, so it correctly should not have been accessible. But showing draft 3 as the old state is confusing in this case.
